# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 786c274b9bd71b2c3ce96e98543bd4aef45a81284b7025ae6c3b2909e089c1ac30d222da828c27c767860a40291089bdd0b5f455de9aaed43fd62eb7f9161e15

test:
  secret_key_base: d71644808c6e4a538ad81b2235074e16c07dc618270910f66d211d3e230fd9c678c509c6007e201700a882c51e1e47fd53141572acf444e144f535b406b56e7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
